// livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import ControleEditoras from './controle/ControleEditoras';
import ControleLivros from './controle/ControleLivros';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Link } from 'react-router-dom';
import { PlusCircle, Trash2, Edit } from 'lucide-react';

const controleEditora = new ControleEditoras();
const controleLivro = new ControleLivros();

export default function LivroLista() {
    const [livros, setLivros] = useState([]);
    const [editoras, setEditoras] = useState([]);
    const [carregado, setCarregado] = useState(false);

    const obterNomeEditora = (codEditora) => {
        const editoraEncontrada = editoras.find(e => e.codEditora === codEditora);
        return editoraEncontrada ? editoraEncontrada.nome : 'Desconhecida';
    };

    useEffect(() => {
        const carregarDados = async () => {
            try {
                const [novosLivros, novasEditoras] = await Promise.all([
                    controleLivro.obterLivros(),
                    controleEditora.obterEditoras()
                ]);

                setLivros(novosLivros);
                setEditoras(novasEditoras); // Armazenar editoras no estado
                setCarregado(true);
            } catch (error) {
                console.error("Erro ao carregar dados:", error);
            }
        };

        if (!carregado) {
            carregarDados();
        }

    }, [carregado]);

    const excluir = (codigoLivro) => {
        controleLivro.excluir(codigoLivro)
            .then(() => {
                setCarregado(false);
            })
            .catch(error => console.error("Erro ao excluir livro:", error));
    };

    const editar = (codigoLivro) => {
        // Redirecionar para página de edição
        window.location.href = `/livroEdita/${codigoLivro}`;
    };

    const LinhaLivro = ({ livro, obterNomeEditora, excluir, editar }) => {
        return (
            <tr>
                <td>{livro.titulo}</td>
                <td>{livro.resumo}</td>
                <td>{obterNomeEditora(livro.codEditora)}</td>
                <td>
                    <ul>
                        {livro.autores.map((autor, index) => (
                            <li key={index}>{autor}</li>
                        ))}
                    </ul>
                </td>
                <td>
                    <div className="d-flex gap-1">
                        <button onClick={() => editar(livro.codigo)} className="btn btn-primary btn-sm" title="Editar">
                            <Edit size={16} />
                        </button>
                        <button onClick={() => excluir(livro.codigo)} className="btn btn-danger btn-sm" title="Excluir">
                            <Trash2 size={16} />
                        </button>
                    </div>
                </td>
            </tr>
        );
    };

    return (
        <main className="container mt-4">
            <div className="d-flex justify-content-between align-items-center mb-3">
                <h1>Catálogo de Livros</h1>
                <Link to="/livroDados" className="btn btn-success" title="Novo Livro">
                    <PlusCircle size={20} />
                </Link>
            </div>
            <table className="table table-striped">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Resumo</th>
                        <th>Editora</th>
                        <th style={{ width: '20%' }}>Autores</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {livros.map((livro, index) => (
                        <LinhaLivro key={index}
                            livro={livro}
                            obterNomeEditora={obterNomeEditora}
                            excluir={excluir}
                            editar={editar} />
                    ))}
                </tbody>
            </table>
        </main>
    );
}

// livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../model/editora';
import { Livro } from '../model/livro';
import { ControleEditorasService } from '../contole/controle-editoras.service';
import { ControleLivrosService } from '../contole/controle-livros.service';
import { Subscription, Observable } from 'rxjs';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})

export class LivroListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  livros: Array<Livro> = [];
  private editorasSubscription: Subscription | undefined;
  private livrosSubscription: Subscription | undefined;

  constructor(private servEditoras: ControleEditorasService,
    private servLivros: ControleLivrosService) { }

  ngOnInit(): void {
    this.carregarEditoras();
    this.carregarLivros();
  }

  carregarEditoras(): void {
    if (this.editorasSubscription) {
      this.editorasSubscription.unsubscribe();
    }
    this.editorasSubscription = this.servEditoras.getEditoras()
      .subscribe((editoras: Editora[]) => {
        this.editoras = editoras;
      });
  }
  carregarLivros(): void {
    if (this.livrosSubscription) {
      this.livrosSubscription.unsubscribe();
    }
    this.livrosSubscription = this.servLivros.obterLivros()
      .subscribe((livros: Livro[]) => {
        this.livros = livros;
      });
  }

  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo).subscribe(() => {
      this.carregarLivros();
    });
  }

  getNomeEditora(codEditora: number): string {
    const editoraEncontrada = this.editoras
      .find(e => e.codEditora == codEditora);
    return editoraEncontrada ? editoraEncontrada.nome : 'Desconhecida';
  }

  ngOnDestroy(): void {
    if (this.livrosSubscription) {
      this.livrosSubscription.unsubscribe();
    }
  }
}


<main class="container mt-4">
    <div class="page-header mb-4 d-flex justify-content-between align-items-center">
        <h1>Catálogo de Livros</h1>
        <a class="btn btn-primary" [routerLink]="['/livroDados']" title="Novo Livro" aria-label="Novo Livro">➕</a>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <tr class="bg-dark text-white fs-5">
                <td class="p-2">Título</td>
                <td class="p-2">Resumo</td>
                <td class="p-2">Editora</td>
                <td class="p-2">Autores</td>
                <td class="p-2 text-center">Ações</td>
            </tr>
            <tr *ngFor="let livro of livros">
                <td class="col-md-3">{{livro.titulo}}</td>
                <td class="col-md-5">{{livro.resumo}}</td>
                <td class="col-md-2">{{getNomeEditora(livro.codEditora)}}</td>
                <td class="col-md-1">
                    <ul *ngFor="let autor of livro.autores">
                        <li>{{autor}}</li>
                    </ul>
                </td>
                <td class="col-md-1 text-end">
                    <a class="btn btn-sm btn-secondary me-2" [routerLink]="['/livroDados', livro.codigo]" title="Editar" aria-label="Editar">✏️</a>
                    <button type="button" class="btn btn-sm btn-danger" (click)="excluir(livro.codigo.toString())" title="Excluir" aria-label="Excluir">🗑️</button>
                </td>
            </tr>
        </table>
    </div>
</main>
