// livros-angular/src/app/editora-lista/editora-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../model/editora';
import { ControleEditorasService } from '../contole/controle-editoras.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './editora-lista.component.html',
  styleUrls: ['./editora-lista.component.css']
})

export class EditoraListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  private editorasSubscription: Subscription | undefined;

  constructor(private servEditora: ControleEditorasService) { }

  ngOnInit(): void {
    this.carregarEditoras();
  }

  carregarEditoras(): void {
    if (this.editorasSubscription) {
      this.editorasSubscription.unsubscribe();
    }
    this.editorasSubscription = this.servEditora.getEditoras()
      .subscribe((editoras: Editora[]) => {
        this.editoras = editoras;
      });
  }

  excluir = (codigo: string): void => {
    this.servEditora.excluir(codigo).subscribe(() => {
      this.carregarEditoras();
    });
  }

  ngOnDestroy(): void {
    if (this.editorasSubscription) {
      this.editorasSubscription.unsubscribe();
    }
  }
}


<main class="container mt-4">
    <div class="page-header mb-4 d-flex justify-content-between align-items-center">
        <h1>Catálogo de Editoras</h1>
        <a class="btn btn-primary" [routerLink]="['/editoraDados']" title="Nova Editora" aria-label="Nova Editora">➕</a>
    </div>

    <div class="table-responsive">
        <table class="table table-hover">
            <tr class="bg-dark text-white fs-5">
                <td class="p-2">Código</td>
                <td class="p-2">Nome</td>
                <td class="p-2 text-center">Ações</td>
            </tr>
            <tr *ngFor="let editora of editoras">
                <td class="col-md-2">{{editora.codEditora}}</td>
                <td class="col-md-6">{{editora.nome}}</td>
                <td class="col-md-2 text-end">
                    <a class="btn btn-sm btn-secondary me-2" [routerLink]="['/editoraDados', editora.codigo]" title="Editar" aria-label="Editar">✏️</a>
                    <button type="button" class="btn btn-sm btn-danger" (click)="excluir(editora.codigo.toString())" title="Excluir" aria-label="Excluir">🗑️</button>
                </td>
            </tr>
        </table>
    </div>
</main>

// livros-react/src/EditoraLista.js
import React, { useState, useEffect } from 'react';
import ControleEditoras from './controle/ControleEditoras';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Link } from 'react-router-dom';
import { PlusCircle, Trash2, Edit } from 'lucide-react';

const controleEditora = new ControleEditoras();

export default function EditoraLista() {
    const [editoras, setEditoras] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        controleEditora.obterEditoras()
            .then(novasEditoras => {
                setEditoras(novasEditoras);
                setCarregado(true);
            })
            .catch(error => console.error("Erro ao obter editoras:", error));

    }, [carregado]);

    const excluir = (codigoEditora) => {
        controleEditora.excluir(codigoEditora)
            .then(() => {
                setCarregado(false);
            })
            .catch(error => console.error("Erro ao excluir editora:", error));
    };

    const editar = (codigoEditora) => {
        // Redirecionar para página de edição
        window.location.href = `/editoraEdita/${codigoEditora}`;
    };

    const LinhaEditora = ({ editora, excluir, editar }) => {
        return (
            <tr>
                <td>{editora.codEditora}</td>
                <td>{editora.nome}</td>
                <td>
                    <div className="d-flex gap-1">
                        <button onClick={() => editar(editora.codigo)} className="btn btn-primary btn-sm" title="Editar">
                            <Edit size={16} />
                        </button>
                        <button onClick={() => excluir(editora.codigo)} className="btn btn-danger btn-sm" title="Excluir">
                            <Trash2 size={16} />
                        </button>
                    </div>
                </td>
            </tr>
        );
    };

    return (
        <main className="container mt-4">
            <div className="d-flex justify-content-between align-items-center mb-3">
                <h1>Catálogo de Editoras</h1>
                <Link to="/editoraDados" className="btn btn-success" title="Nova Editora">
                    <PlusCircle size={20} />
                </Link>
            </div>
            <table className="table table-striped">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nome</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {editoras.map((editora, index) => (
                        <LinhaEditora key={index} editora={editora} excluir={excluir} editar={editar} />
                    ))}
                </tbody>
            </table>
        </main>
    );
}
