// livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Editora } from '../model/editora';
import { Livro } from '../model/livro';
import { ControleEditorasService } from '../contole/controle-editoras.service';
import { ControleLivrosService } from '../contole/controle-livros.service';
import { Observable } from 'rxjs';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})

export class LivroDadosComponent implements OnInit, OnDestroy {
  router: Router;
  livro: Livro = new Livro();
  autoresForm: string = "";
  editoras: Array<Editora>;
  private routeSub: Subscription | undefined;

  constructor(router: Router,
    private servEditora: ControleEditorasService,
    private servLivros: ControleLivrosService,
    private route: ActivatedRoute) {
    this.router = router;
    this.editoras = [];
  }

  ngOnInit(): void {
    this.servEditora.getEditoras().subscribe(data => {
      this.editoras = data;
    });

    const snapshotCodigo = this.route.snapshot.paramMap.get('codigo');
    if (snapshotCodigo) {
      this.servLivros.getLivroById(snapshotCodigo).subscribe(livro => {
        if (livro) {
          this.livro = livro;
          this.autoresForm = (livro.autores || []).join('\n');
        }
      });
    }

    this.routeSub = this.route.params.subscribe(params => {
      const codigo = params['codigo'];
      if (codigo) {
        this.servLivros.getLivroById(codigo).subscribe(livro => {
          if (livro) {
            this.livro = livro;
            this.autoresForm = (livro.autores || []).join('\n');
          }
        });
      }
    });
  }

  incluir = (livro: Livro): void => {
    livro.autores = this.autoresForm.split('\n');
    const inclusao$: Observable<boolean> = this.servLivros.incluir(livro);
    inclusao$.subscribe({
      next: (success: boolean) => {
        if (success) {
          this.router.navigateByUrl("/livroLista");
        } else {
          console.log("Inclusão falhou (retornou falso).");
        }
      },
      error: (err) => {
        console.error("Erro durante a inclusão:", err);
      },
      complete: () => {
        console.log("Inclusão completa.");
      }
    });
  }

  salvar = (livro: Livro): void => {
    livro.autores = this.autoresForm.split('\n');
    if (livro && livro.codigo) {
      this.servLivros.alterar(livro).subscribe({
        next: (success: boolean) => {
          if (success) {
            this.router.navigateByUrl('/livroLista');
          } else {
            console.log('Alteração falhou (retornou falso).');
          }
        },
        error: err => console.error('Erro ao alterar livro:', err)
      });
    } else {
      this.incluir(livro);
    }
  }

  ngOnDestroy(): void {
    if (this.routeSub) {
      this.routeSub.unsubscribe();
    }
  }
}

<main class="container mt-4">
    <div class="page-header mb-4">
        <h1>Dados do Livro</h1>
    </div>

    <form (submit)="salvar(livro)">
        <div class="form-group">
            <label for="livro">Título:</label>
            <input type="text" class="form-control" name="titulo" [(ngModel)]="livro.titulo"><br />
        </div>
        <label for="resumo">Resumo:</label>
        <input type="text" class="form-control" name="resumo" [(ngModel)]="livro.resumo"><br />
        <label for="editora">Editora:</label>
        <select id="meuSelect" class="form-control custom-select dropdown-toggle" [(ngModel)]="livro.codEditora"
            [ngModelOptions]="{standalone: true}">
            <option *ngFor="let editora of editoras" [value]="editora.codEditora">
                {{ editora.nome }}
            </option>
        </select><br />
        <label for="autores">Autores (1 por linha):</label>
        <textarea class="form-control" name="autores" [(ngModel)]="autoresForm" rows="3"></textarea><br />
        <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>

</main>

// livros-next/app/pages/LivroDados/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import AutoBreadcrumbs from '../../components/AutoBreadcrumbs';
import { useRouter, useSearchParams } from 'next/navigation';
import ControleEditoras from '../../controle/ControleEditoras';
import ControleLivros from '../../controle/ControleLivros';
import Livro from '../../model/Livro';
import Editora from '../../model/Editora';

const controleEditora = new ControleEditoras();
const controleLivro = new ControleLivros();

export default function LivroDados() {
    const navigate = useRouter();
    const params = useSearchParams();
    const id = params?.get('id');
    const [isEdit, setIsEdit] = useState(false);
    const [loading, setLoading] = useState(false);
    const [loadError, setLoadError] = useState<string | null>(null);

    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [codEditora, setCodEditora] = useState<number | string>(0);
    const [editoras, setEditoras] = useState<Editora[]>([])
    const [autores, setAutores] = useState('');
    const [codigoInterno, setCodigoInterno] = useState('');

    useEffect(() => {
        controleEditora.obterEditoras()
            .then(listaEditoras => {
                setEditoras(listaEditoras);
                if (listaEditoras.length > 0) {
                    setCodEditora(listaEditoras[0].codEditora);
                }
            })
            .catch(error => console.error("Erro ao obter editoras:", error));
    }, []);

    useEffect(() => {
        if (id) {
            setLoading(true);
            setLoadError(null);
            controleLivro.obter(id)
                .then(l => {
                    if (l) {
                        setIsEdit(true);
                        setCodigoInterno(l.codigo || '');
                        setTitulo(l.titulo);
                        setResumo(l.resumo);
                        setCodEditora(l.codEditora);
                        setAutores((l.autores || []).join('\n'));
                    } else {
                        setLoadError('Livro não encontrado.');
                    }
                })
                .catch(err => {
                    console.error('Erro ao carregar livro:', err);
                    setLoadError('Erro ao carregar livro. Veja o console.');
                })
                .finally(() => setLoading(false));
        }
    }, [id]);

    const incluir = (event: React.FormEvent) => {
        event.preventDefault();
        
        const codEditoraNumber = Number(codEditora);
        
        const novoLivro = new Livro(
            "",
            codEditoraNumber,
            titulo,
            resumo,
            autores.split('\n').map(autor => autor.trim()).filter(Boolean)
        );

        controleLivro.incluir(novoLivro)
            .then(() => {
                navigate.push('/pages/LivroLista');
            })
            .catch(error => console.error("Erro ao incluir livro:", error));
    };

    const salvar = (event: React.FormEvent) => {
        event.preventDefault();
        const codEditoraNumber = Number(codEditora);
        const livroAtual = new Livro(codigoInterno, codEditoraNumber, titulo, resumo, autores.split('\n').map(a => a.trim()).filter(Boolean));
        controleLivro.atualizar(livroAtual)
            .then(() => navigate.push('/pages/LivroLista'))
            .catch(err => console.error('Erro ao atualizar livro:', err));
    };

    return (
        <main className="container mt-4">
            <AutoBreadcrumbs />
            <h1>{isEdit ? 'Edição de Livro' : 'Inclusão de Livro'}</h1>
            {id && loading ? (
                <p>Carregando livro...</p>
            ) : id && loadError ? (
                <div className="alert alert-warning">{loadError}</div>
            ) : (
                <form onSubmit={isEdit ? salvar : incluir}>
                <div className="mb-3">
                    <label htmlFor="titulo" className="form-label">Título</label>
                    <input type="text" className="form-control" id="titulo" value={titulo} onChange={(e) => setTitulo(e.target.value)} required />
                </div>

                <div className="mb-3">
                    <label htmlFor="resumo" className="form-label">Resumo</label>
                    <textarea className="form-control" id="resumo" rows={3} value={resumo} onChange={(e) => setResumo(e.target.value)} required></textarea>
                </div>

                <div className="mb-3">
                    <label htmlFor="codEditora" className="form-label">Editora</label>
                    <select
                        className="form-select"
                        id="codEditora"
                        value={codEditora}
                        onChange={(e) => setCodEditora(e.target.value)}
                        required
                    >
                        {editoras.map((editora) => (
                            <option key={editora.codEditora} value={editora.codEditora}>
                                {editora.nome}
                            </option>
                        ))}
                    </select>
                </div>

                <div className="mb-3">
                    <label htmlFor="autores" className="form-label">Autores (um por linha)</label>
                    <textarea className="form-control" id="autores" rows={3} value={autores} onChange={(e) => setAutores(e.target.value)} required></textarea>
                </div>

                    <button type="submit" className="btn btn-primary">{isEdit ? 'Salvar Alterações' : 'Incluir Livro'}</button>
                </form>
            )}
        </main>
    );
}
